<a href="https://colab.research.google.com/github/sarthakp972/machine_learning_3.1/blob/main/day3_new.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [ ]:
df=pd.read_excel('/content/drive/MyDrive/Machine_learning_15 01 2024/Salary_Dataset_02.xls')

In [ ]:
df

    Australia  Canada  Dubai  USA  Salary  YearsExperience  Purchased
0           0       0      1    0   39343              1.1          0
1           0       1      0    0   46205              1.3          1
2           0       1      0    0   37731              1.5          0
3           0       1      0    0   43525              2.0          0
4           0       0      0    1   39891              2.2          0
5           0       0      1    0   56642              2.9          0
6           0       1      0    0   60150              3.0          1
7           1       0      0    0   54445              3.2          0
8           0       0      1    0   64445              3.2          1
9           0       0      1    0   57189              3.7          0
10          0       0      1    0   63218              3.9          1
11          0       0      0    1   55794              4.0          0
12          0       0      1    0   56957              4.0          1
13          0       1      0    0   57081              4.1          0
14          1       0      0    0   61111              4.5          0
15          0       0      0    1   67938              4.9          0
16          0       0      0    1   66029              5.1          0
17          0       1      0    0   83088              5.3          0
18          1       0      0    0   81363              5.9          1
19          0       1      0    0   93940              6.0          0
20          0       1      0    0   91738              6.8          0
21          1       0      0    0   98273              7.1          0
22          1       0      0    0  101302              7.9          0
23          1       0      0    0  113812              8.2          1
24          0       0      1    0  109431              8.7          0
25          1       0      0    0  105582              9.0          1
26          0       0      1    0  116969              9.5          0
27          0       0      0    1  112635              9.6          1
28          0       0      0    1  122391             10.3          0
29          0       1      0    0  121872             10.5          1

#iloc
it is using for acces  individual  data


iloc=Location by index
iloc[rows,columns]
iloc[row Range , column range]
iloc[start row :End row, start column :End Column]
column Last index starts from -1
[Row , index , column index ]

In [ ]:
x=df.iloc[2,5]
x

1.5

In [ ]:
x=df.iloc[2,4]
x

37731

In [ ]:
x=df.iloc[5,-2]
x

2.9

In [ ]:
#upper bound does not included in range
#a=df.iloc[2,:]
a= df.iloc[2,0:7]
a

Australia              0.0
Canada                 1.0
Dubai                  0.0
USA                    0.0
Salary             37731.0
YearsExperience        1.5
Purchased              0.0
Name: 2, dtype: float64

In [ ]:
x=df.iloc[:,:-1]
x

    Australia  Canada  Dubai  USA  Salary  YearsExperience
0           0       0      1    0   39343              1.1
1           0       1      0    0   46205              1.3
2           0       1      0    0   37731              1.5
3           0       1      0    0   43525              2.0
4           0       0      0    1   39891              2.2
5           0       0      1    0   56642              2.9
6           0       1      0    0   60150              3.0
7           1       0      0    0   54445              3.2
8           0       0      1    0   64445              3.2
9           0       0      1    0   57189              3.7
10          0       0      1    0   63218              3.9
11          0       0      0    1   55794              4.0
12          0       0      1    0   56957              4.0
13          0       1      0    0   57081              4.1
14          1       0      0    0   61111              4.5
15          0       0      0    1   67938              4.9
16          0       0      0    1   66029              5.1
17          0       1      0    0   83088              5.3
18          1       0      0    0   81363              5.9
19          0       1      0    0   93940              6.0
20          0       1      0    0   91738              6.8
21          1       0      0    0   98273              7.1
22          1       0      0    0  101302              7.9
23          1       0      0    0  113812              8.2
24          0       0      1    0  109431              8.7
25          1       0      0    0  105582              9.0
26          0       0      1    0  116969              9.5
27          0       0      0    1  112635              9.6
28          0       0      0    1  122391             10.3
29          0       1      0    0  121872             10.5

In [ ]:
x.shape

(30, 6)

In [ ]:
y=df.iloc[:,-1]
y

0     0
1     1
2     0
3     0
4     0
5     0
6     1
7     0
8     1
9     0
10    1
11    0
12    1
13    0
14    0
15    0
16    0
17    0
18    1
19    0
20    0
21    0
22    0
23    1
24    0
25    1
26    0
27    1
28    0
29    1
Name: Purchased, dtype: int64

In [ ]:
y.shape

(30,)

#Train set splitting
search sklearn slitting data set

In [ ]:
x_train, x_test, y_train, y_test = train_test_split( x, y, test_size=0.2,random_state=42)

In [ ]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((24, 6), (6, 6), (24,), (6,))

In [ ]:
x_train

    Australia  Canada  Dubai  USA  Salary  YearsExperience
28          0       0      0    1  122391             10.3
24          0       0      1    0  109431              8.7
12          0       0      1    0   56957              4.0
0           0       0      1    0   39343              1.1
4           0       0      0    1   39891              2.2
16          0       0      0    1   66029              5.1
5           0       0      1    0   56642              2.9
13          0       1      0    0   57081              4.1
11          0       0      0    1   55794              4.0
22          1       0      0    0  101302              7.9
1           0       1      0    0   46205              1.3
2           0       1      0    0   37731              1.5
25          1       0      0    0  105582              9.0
3           0       1      0    0   43525              2.0
21          1       0      0    0   98273              7.1
26          0       0      1    0  116969              9.5
18          1       0      0    0   81363              5.9
29          0       1      0    0  121872             10.5
20          0       1      0    0   91738              6.8
7           1       0      0    0   54445              3.2
10          0       0      1    0   63218              3.9
14          1       0      0    0   61111              4.5
19          0       1      0    0   93940              6.0
6           0       1      0    0   60150              3.0